/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizDomainRouteImport } from './routes/quiz.$domain'
import { Route as InterviewDomainRouteImport } from './routes/interview.$domain'
import { Route as DomainDomainRouteImport } from './routes/domain.$domain'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizDomainRoute = QuizDomainRouteImport.update({
  id: '/quiz/$domain',
  path: '/quiz/$domain',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewDomainRoute = InterviewDomainRouteImport.update({
  id: '/interview/$domain',
  path: '/interview/$domain',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainDomainRoute = DomainDomainRouteImport.update({
  id: '/domain/$domain',
  path: '/domain/$domain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evaluation': typeof EvaluationRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/progress': typeof ProgressRoute
  '/domain/$domain': typeof DomainDomainRoute
  '/interview/$domain': typeof InterviewDomainRoute
  '/quiz/$domain': typeof QuizDomainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evaluation': typeof EvaluationRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/progress': typeof ProgressRoute
  '/domain/$domain': typeof DomainDomainRoute
  '/interview/$domain': typeof InterviewDomainRoute
  '/quiz/$domain': typeof QuizDomainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evaluation': typeof EvaluationRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/progress': typeof ProgressRoute
  '/domain/$domain': typeof DomainDomainRoute
  '/interview/$domain': typeof InterviewDomainRoute
  '/quiz/$domain': typeof QuizDomainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/evaluation'
    | '/login'
    | '/pricing'
    | '/progress'
    | '/domain/$domain'
    | '/interview/$domain'
    | '/quiz/$domain'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/evaluation'
    | '/login'
    | '/pricing'
    | '/progress'
    | '/domain/$domain'
    | '/interview/$domain'
    | '/quiz/$domain'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/evaluation'
    | '/login'
    | '/pricing'
    | '/progress'
    | '/domain/$domain'
    | '/interview/$domain'
    | '/quiz/$domain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EvaluationRoute: typeof EvaluationRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProgressRoute: typeof ProgressRoute
  DomainDomainRoute: typeof DomainDomainRoute
  InterviewDomainRoute: typeof InterviewDomainRoute
  QuizDomainRoute: typeof QuizDomainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$domain': {
      id: '/quiz/$domain'
      path: '/quiz/$domain'
      fullPath: '/quiz/$domain'
      preLoaderRoute: typeof QuizDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$domain': {
      id: '/interview/$domain'
      path: '/interview/$domain'
      fullPath: '/interview/$domain'
      preLoaderRoute: typeof InterviewDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain/$domain': {
      id: '/domain/$domain'
      path: '/domain/$domain'
      fullPath: '/domain/$domain'
      preLoaderRoute: typeof DomainDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EvaluationRoute: EvaluationRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProgressRoute: ProgressRoute,
  DomainDomainRoute: DomainDomainRoute,
  InterviewDomainRoute: InterviewDomainRoute,
  QuizDomainRoute: QuizDomainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
