import { Domain } from "../lib/knowledge";

export type QuizQuestion = {
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
};

export const QUIZ_BANK: Record<Domain, QuizQuestion[]> = {
  dsa: [
    { question: "What is the time complexity of searching in a balanced Binary Search Tree?", options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"], correctIndex: 2, explanation: "In a balanced BST, each comparison eliminates half of the remaining tree." },
    { question: "Which data structure is best for implementing a LRU Cache?", options: ["Array + Linked List", "Hash Map + Doubly Linked List", "Binary Tree + Queue", "Stack + Hash Map"], correctIndex: 1, explanation: "Hash Map gives O(1) access, Doubly Linked List allows O(1) removal and insertion at the ends." },
    { question: "What algorithm is used to find the shortest path in a graph with unweighted edges?", options: ["Dijkstra's Algorithm", "Depth First Search", "Breadth First Search", "Kruskal's Algorithm"], correctIndex: 2, explanation: "BFS explores level by level, guaranteeing the shortest path in unweighted graphs." },
    { question: "What is the worst-case time complexity of QuickSort?", options: ["O(n log n)", "O(n)", "O(n^2)", "O(log n)"], correctIndex: 2, explanation: "If the pivot is always the smallest or largest element, the partitioning is extremely unbalanced, leading to O(n^2)." },
    { question: "Which algorithm detects a cycle in a directed graph?", options: ["Kruskal's Algorithm", "Floyd-Warshall", "Depth First Search (DFS)", "Binary Search"], correctIndex: 2, explanation: "DFS can detect a cycle by keeping track of the recursion stack (visited vs visiting)." },
    { question: "What is the space complexity of a recursive DFS on a balanced tree?", options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"], correctIndex: 2, explanation: "The maximum depth of the recursion stack is the height of the tree, which is O(log n)." },
    { question: "Which sorting algorithm is NOT stable by default?", options: ["Merge Sort", "Insertion Sort", "Bubble Sort", "Quick Sort"], correctIndex: 3, explanation: "Quick Sort swaps non-adjacent elements, which can change the relative order of equal elements." },
    { question: "What is the time complexity of building a Max Heap from an array of n elements?", options: ["O(n log n)", "O(n)", "O(log n)", "O(1)"], correctIndex: 1, explanation: "Using the bottom-up approach (heapify), building a heap takes O(n) time." },
    { question: "Which data structure uses LIFO (Last In First Out)?", options: ["Queue", "Stack", "Tree", "Graph"], correctIndex: 1, explanation: "Stacks operate on a Last In First Out principle." },
    { question: "What is a Trie typically used for?", options: ["Shortest path algorithms", "Prefix matching and autocomplete", "Sorting numbers", "Balancing binary trees"], correctIndex: 1, explanation: "A Trie (prefix tree) efficiently stores strings and allows fast prefix lookups." },
    { question: "In dynamic programming, what is memoization?", options: ["Solving subproblems bottom-up", "Caching results of recursive calls", "Optimizing memory usage by discarding old data", "Converting recursion to iteration"], correctIndex: 1, explanation: "Memoization is a top-down approach where results of expensive function calls are cached." },
    { question: "What is the time complexity to insert at the front of a Singly Linked List?", options: ["O(1)", "O(n)", "O(log n)", "O(n^2)"], correctIndex: 0, explanation: "Inserting at the head only requires changing the head pointer and the new node's next pointer." },
    { question: "Which graph traversal is used in topological sorting?", options: ["BFS", "DFS", "Both BFS and DFS can be used", "Neither"], correctIndex: 2, explanation: "Kahn's algorithm uses BFS, while the standard recursive approach uses DFS." },
    { question: "What is the purpose of a Sentinel Node in a Linked List?", options: ["To store the maximum value", "To simplify boundary conditions", "To point to the middle element", "To compress the list"], correctIndex: 1, explanation: "Sentinel (dummy) nodes eliminate the need to check for null pointers at the head or tail." },
    { question: "Which of the following problems can be solved using the Sliding Window technique?", options: ["Longest Palindromic Substring", "Longest Substring Without Repeating Characters", "Traveling Salesperson", "Matrix Chain Multiplication"], correctIndex: 1, explanation: "Sliding window efficiently tracks a contiguous subarray/substring that meets a condition." },
    { question: "What is the time complexity of the Floyd-Warshall algorithm?", options: ["O(V+E)", "O(V^2)", "O(V^3)", "O(E log V)"], correctIndex: 2, explanation: "It uses three nested loops over the vertices to find all-pairs shortest paths." },
    { question: "Which algorithmic paradigm does Dijkstra's algorithm follow?", options: ["Dynamic Programming", "Divide and Conquer", "Greedy", "Backtracking"], correctIndex: 2, explanation: "It always picks the unvisited vertex with the smallest known distance (greedy choice)." },
    { question: "How do you find the middle of a Linked List in one pass?", options: ["Hash Map", "Two Pointers (Slow and Fast)", "Stack", "Binary Search"], correctIndex: 1, explanation: "The fast pointer moves two steps while the slow pointer moves one. When fast reaches the end, slow is at the middle." },
    { question: "What is the time complexity of looking up a value in a Hash Table (worst case)?", options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], correctIndex: 2, explanation: "If all elements hash to the same bucket (collision), lookup degrades to O(n)." },
    { question: "Which algorithm finds the Minimum Spanning Tree?", options: ["Dijkstra's", "Bellman-Ford", "Kruskal's", "Floyd-Warshall"], correctIndex: 2, explanation: "Kruskal's algorithm (along with Prim's) is used to find an MST." }
  ],
  springboot: [
    { question: "What is the default embedded server in Spring Boot?", options: ["Jetty", "Undertow", "Tomcat", "GlassFish"], correctIndex: 2, explanation: "Spring Boot uses Apache Tomcat as the default embedded web server." },
    { question: "Which annotation is used to mark a class as a RESTful controller?", options: ["@Controller", "@RestController", "@WebController", "@APIController"], correctIndex: 1, explanation: "@RestController is a convenience annotation that combines @Controller and @ResponseBody." },
    { question: "What does @SpringBootApplication do?", options: ["It replaces @Configuration, @EnableAutoConfiguration, and @ComponentScan", "It starts the Tomcat server", "It configures the database connection", "It creates the main method"], correctIndex: 0, explanation: "It is a meta-annotation that pulls in component scanning, auto-configuration, and configuration support." },
    { question: "Which annotation injects dependencies in Spring?", options: ["@Injectable", "@Autowired", "@Provide", "@Bean"], correctIndex: 1, explanation: "@Autowired automatically injects the required bean by type." },
    { question: "How do you externalize configuration in Spring Boot?", options: ["Using XML files only", "Using application.properties or application.yml", "By hardcoding in configuration classes", "Through the pom.xml file"], correctIndex: 1, explanation: "Spring Boot reads properties from application.properties or application.yml by default." },
    { question: "What is Spring Boot Actuator used for?", options: ["Security authentication", "Monitoring and managing the application", "Database migrations", "Creating REST APIs"], correctIndex: 1, explanation: "Actuator provides built-in endpoints (like /health, /metrics) for monitoring." },
    { question: "What is the purpose of @Transactional?", options: ["To define a REST endpoint", "To manage database transactions automatically", "To inject a repository", "To log method execution time"], correctIndex: 1, explanation: "It ensures a method executes within a database transaction, rolling back on runtime exceptions." },
    { question: "Which dependency is required for Spring Data JPA?", options: ["spring-boot-starter-web", "spring-boot-starter-jdbc", "spring-boot-starter-data-jpa", "spring-data-hibernate"], correctIndex: 2, explanation: "The data-jpa starter brings in Hibernate, Spring Data, and related dependencies." },
    { question: "How can you run code at application startup?", options: ["Implement CommandLineRunner or ApplicationRunner", "Use @Startup annotation", "Put code in the constructor of a Controller", "Use @BeforeStart"], correctIndex: 0, explanation: "Both interfaces provide a run() method that executes right after the context is loaded." },
    { question: "What is the default scope of a Spring Bean?", options: ["Prototype", "Request", "Session", "Singleton"], correctIndex: 3, explanation: "By default, Spring creates only one instance of a bean per application context." },
    { question: "How do you handle exceptions globally in Spring MVC?", options: ["Using @GlobalException", "Using @ControllerAdvice", "Using try-catch in every method", "Using @ExceptionHandler on the main class"], correctIndex: 1, explanation: "@ControllerAdvice allows you to handle exceptions across the whole application in one global component." },
    { question: "What does the 'N+1 query problem' refer to in Hibernate?", options: ["Executing N queries instead of 1 due to lazy loading of collections", "A bug in SQL syntax", "Inserting N records one by one", "Pagination offset logic"], correctIndex: 0, explanation: "It happens when an ORM executes 1 query to get parent entities, and N additional queries to fetch their children." },
    { question: "Which annotation reads values from application.properties?", options: ["@Env", "@Value", "@Property", "@Inject"], correctIndex: 1, explanation: "@Value(\"${property.name}\") injects the value of a property." },
    { question: "What is the purpose of Spring Profiles?", options: ["To profile memory usage", "To map different URLs", "To segregate parts of application configuration for different environments", "To create user profiles"], correctIndex: 2, explanation: "Profiles allow activating different beans or configurations based on the environment (e.g., dev, prod)." },
    { question: "Which method of dependency injection is most recommended by the Spring team?", options: ["Field Injection", "Setter Injection", "Constructor Injection", "Interface Injection"], correctIndex: 2, explanation: "Constructor injection allows fields to be final, promotes immutability, and makes testing easier." },
    { question: "What is HikariCP in Spring Boot?", options: ["A JSON parser", "A security filter", "The default JDBC connection pool", "A caching provider"], correctIndex: 2, explanation: "HikariCP is a very fast and lightweight JDBC connection pool used by default." },
    { question: "How do you enable Cross-Origin Resource Sharing (CORS)?", options: ["@CrossOrigin", "@CorsEnable", "@AllowOrigin", "It is enabled by default"], correctIndex: 0, explanation: "The @CrossOrigin annotation can be applied at the controller or method level to allow cross-origin requests." },
    { question: "What does @ConditionalOnProperty do?", options: ["Creates a bean only if a property is present and matches a value", "Validates request parameters", "Conditionally redirects URLs", "Applies a CSS property"], correctIndex: 0, explanation: "It's used in auto-configuration to load beans based on configuration properties." },
    { question: "How can you validate a request body in a Spring REST controller?", options: ["@Check", "@Valid or @Validated", "@AssertTrue", "@ValidateBody"], correctIndex: 1, explanation: "@Valid triggers validation on the annotated object, throwing an exception if constraints are violated." },
    { question: "What is the role of the DispatcherServlet?", options: ["It manages database connections", "It is the front controller that routes HTTP requests to the appropriate handler", "It sends emails", "It serves static HTML files only"], correctIndex: 1, explanation: "DispatcherServlet acts as the Front Controller, routing incoming requests to controllers." }
  ],
  system_design: [
    { question: "What is the CAP Theorem?", options: ["Consistency, Availability, Partition Tolerance", "Concurrency, Availability, Persistence", "Consistency, Asynchrony, Partitioning", "Caching, Availability, Performance"], correctIndex: 0, explanation: "CAP theorem states a distributed system can only provide two of the three simultaneously." },
    { question: "Which caching strategy writes data to the cache and database simultaneously?", options: ["Write-behind", "Write-through", "Cache-aside", "Read-through"], correctIndex: 1, explanation: "Write-through ensures consistency between cache and DB, though it adds write latency." },
    { question: "What is the purpose of Consistent Hashing?", options: ["To encrypt passwords safely", "To minimize key reorganization when nodes are added or removed", "To hash JSON web tokens", "To detect data corruption"], correctIndex: 1, explanation: "It maps keys and nodes on a ring, so adding/removing a node only affects adjacent keys." },
    { question: "In a microservices architecture, what is a Circuit Breaker used for?", options: ["To prevent network loops", "To stop requests to a failing service to prevent cascading failures", "To encrypt traffic between services", "To balance load across nodes"], correctIndex: 1, explanation: "It fails fast when a downstream service is struggling, allowing it time to recover." },
    { question: "What does 'Eventual Consistency' mean?", options: ["Data will always be consistent immediately", "Data will become consistent over time, given no new updates", "Data is consistent only on reads", "Data is never fully consistent"], correctIndex: 1, explanation: "It guarantees that if no new updates are made to a given data item, eventually all accesses will return the last updated value." },
    { question: "Which database is fundamentally a Key-Value store?", options: ["PostgreSQL", "MongoDB", "Redis", "Cassandra"], correctIndex: 2, explanation: "Redis is an in-memory data structure store, used primarily as a key-value database." },
    { question: "What is a Content Delivery Network (CDN) primarily used for?", options: ["Executing backend code", "Caching static assets geographically closer to users", "Storing relational data", "Managing microservice routing"], correctIndex: 1, explanation: "CDNs reduce latency by serving static files from edge servers near the user." },
    { question: "What is the difference between Horizontal and Vertical scaling?", options: ["Horizontal = adding more machines, Vertical = adding more power (CPU/RAM) to one machine", "Horizontal = scaling databases, Vertical = scaling web servers", "They mean the same thing", "Horizontal = adding storage, Vertical = adding compute"], correctIndex: 0, explanation: "Scaling out (horizontal) vs scaling up (vertical)." },
    { question: "Which messaging system is designed as a distributed append-only log?", options: ["RabbitMQ", "ActiveMQ", "Apache Kafka", "Amazon SQS"], correctIndex: 2, explanation: "Kafka is a distributed event streaming platform built around an append-only commit log." },
    { question: "What does 'ACID' stand for in database systems?", options: ["Atomicity, Consistency, Isolation, Durability", "Availability, Concurrency, Integrity, Durability", "Asynchronous, Consistent, Isolated, Distributed", "Authentication, Consistency, Isolation, Database"], correctIndex: 0, explanation: "ACID properties guarantee that database transactions are processed reliably." },
    { question: "How does a 'Token Bucket' algorithm work in rate limiting?", options: ["Tokens are added at a fixed rate; each request consumes a token.", "Tokens leak out at a constant rate.", "Requests are dropped if they exceed a hard limit per minute.", "Tokens are passed between servers in a ring."], correctIndex: 0, explanation: "Token bucket allows bursts of traffic up to the bucket capacity, refilling at a steady rate." },
    { question: "What is a reverse proxy?", options: ["A server that sits in front of backend servers and forwards client requests to them", "A server that routes traffic out to the internet", "A database replication tool", "A DNS resolver"], correctIndex: 0, explanation: "Nginx and HAProxy are common reverse proxies used for load balancing, caching, and SSL termination." },
    { question: "Why might you choose a NoSQL database over a SQL database?", options: ["For strict ACID transactions", "For flexible schemas and high write throughput at scale", "For complex JOIN queries", "To reduce storage costs"], correctIndex: 1, explanation: "NoSQL databases (like Cassandra or MongoDB) scale horizontally more easily and handle unstructured data well." },
    { question: "What is an Idempotency Key used for in APIs?", options: ["To encrypt the payload", "To safely retry a request without causing duplicate side-effects (e.g. double charging)", "To authenticate the user", "To route the request to a specific shard"], correctIndex: 1, explanation: "If a request with the same idempotency key is sent twice, the server processes it only once." },
    { question: "What is Database Sharding?", options: ["Partitioning data horizontally across multiple database servers", "Creating indexes to speed up queries", "Creating read replicas", "Backing up the database to cold storage"], correctIndex: 0, explanation: "Sharding splits a large table into smaller chunks (shards) spread across multiple nodes." },
    { question: "What is the 'Thundering Herd' problem?", options: ["Too many servers crashing at once", "A large number of processes waking up simultaneously to handle an event, causing severe contention", "A database running out of disk space", "Network packets arriving out of order"], correctIndex: 1, explanation: "Often happens when a cache key expires and hundreds of requests simultaneously query the DB to rebuild it." },
    { question: "In a Master-Slave replication setup, how is replication lag defined?", options: ["The time it takes to write to the master", "The delay between a write on the master and it appearing on the slave", "The time to elect a new master", "The ping latency between nodes"], correctIndex: 1, explanation: "Replication lag occurs in async replication where read replicas are slightly behind the primary." },
    { question: "What is the CQRS pattern?", options: ["Command Query Responsibility Segregation - separating read and write models", "Cache Query Routing System", "Consistent Quorum Replication Strategy", "Container Quality Rating System"], correctIndex: 0, explanation: "CQRS uses different models to update information than the model you use to read information." },
    { question: "What role does ZooKeeper typically play in a distributed system?", options: ["Load balancing HTTP traffic", "Serving HTML pages", "Configuration management, synchronization, and naming registry", "Storing large video files"], correctIndex: 2, explanation: "Systems like Kafka historically used ZooKeeper to manage cluster state and metadata." },
    { question: "Which load balancing algorithm sends requests to the server with the fewest active connections?", options: ["Round Robin", "IP Hash", "Least Connections", "Random"], correctIndex: 2, explanation: "Least Connections dynamically routes traffic to the least busy server." }
  ],
  lld: [
    { question: "What does the 'S' in SOLID stand for?", options: ["Singleton Principle", "Single Responsibility Principle", "System Reliability Principle", "Software Reusability Principle"], correctIndex: 1, explanation: "A class should have one, and only one, reason to change." },
    { question: "Which design pattern is used to ensure only one instance of a class exists?", options: ["Factory", "Observer", "Singleton", "Decorator"], correctIndex: 2, explanation: "The Singleton pattern restricts instantiation of a class to a single object." },
    { question: "What is the Observer pattern used for?", options: ["Creating objects without specifying the exact class", "Defining a one-to-many dependency so that when one object changes state, its dependents are notified", "Iterating over a collection", "Encapsulating a request as an object"], correctIndex: 1, explanation: "It is heavily used in event-driven systems and UI frameworks (Pub/Sub)." },
    { question: "Which principle states that subclasses should be substitutable for their base classes?", options: ["Dependency Inversion", "Open/Closed Principle", "Liskov Substitution Principle", "Interface Segregation"], correctIndex: 2, explanation: "LSP ensures that inheritance is used correctly without breaking expected behavior." },
    { question: "What is the purpose of the Factory Method pattern?", options: ["To create an instance of a class without exposing the instantiation logic to the client", "To limit memory usage by sharing objects", "To attach additional responsibilities to an object dynamically", "To represent an operation to be performed on elements of an object structure"], correctIndex: 0, explanation: "It delegates the creation of objects to subclasses." },
    { question: "How does the Decorator pattern differ from inheritance?", options: ["It adds behavior dynamically at runtime using composition", "It removes behavior", "It is compiled statically", "There is no difference"], correctIndex: 0, explanation: "Decorator wraps an object to add behavior without creating a massive subclass hierarchy." },
    { question: "Which pattern encapsulates an algorithm inside a class, allowing them to be interchangeable?", options: ["State Pattern", "Strategy Pattern", "Template Method", "Command Pattern"], correctIndex: 1, explanation: "Strategy pattern lets the algorithm vary independently from clients that use it." },
    { question: "What is the Open/Closed Principle?", options: ["Classes should be open for extension but closed for modification", "Software should be open source", "Database connections should be closed automatically", "Methods should be open to all packages"], correctIndex: 0, explanation: "You should be able to add new functionality without touching existing tested code." },
    { question: "Which pattern is used to construct a complex object step by step?", options: ["Prototype", "Abstract Factory", "Builder", "Facade"], correctIndex: 2, explanation: "Builder separates the construction of a complex object from its representation." },
    { question: "What does the Facade pattern provide?", options: ["A unified, simplified interface to a set of interfaces in a subsystem", "A way to duplicate objects", "A method to delay object creation", "A way to traverse a tree"], correctIndex: 0, explanation: "Facade hides the complexities of a larger system behind a simpler API." },
    { question: "What is Dependency Injection?", options: ["Injecting SQL into a database", "A technique where an object receives other objects that it depends on, rather than creating them itself", "A method to load DLLs at runtime", "Injecting environment variables into code"], correctIndex: 1, explanation: "DI implements Inversion of Control, making code modular and testable." },
    { question: "Which pattern allows an object to alter its behavior when its internal state changes?", options: ["State Pattern", "Strategy Pattern", "Observer Pattern", "Memento Pattern"], correctIndex: 0, explanation: "The State pattern encapsulates state-specific behaviors in separate classes." },
    { question: "What is the Interface Segregation Principle?", options: ["Interfaces should be as large as possible", "No client should be forced to depend on methods it does not use", "Interfaces must be segregated into different packages", "Classes should not implement interfaces"], correctIndex: 1, explanation: "Prefer many small, client-specific interfaces over one 'fat' interface." },
    { question: "What does 'Composition over Inheritance' mean?", options: ["Inheritance should never be used", "Classes should achieve polymorphic behavior and code reuse by containing other classes rather than extending them", "Composing music is harder than inheriting it", "Multiple inheritance is preferred in Java"], correctIndex: 1, explanation: "Composition provides greater flexibility and avoids the fragile base class problem." },
    { question: "Which pattern represents a request as an object, allowing parameterization of clients with queues or logs?", options: ["Command Pattern", "Chain of Responsibility", "Mediator", "Visitor"], correctIndex: 0, explanation: "Command encapsulates all data required for an action (e.g., used for Undo operations)." },
    { question: "What is the primary benefit of the Flyweight pattern?", options: ["Minimizing memory usage by sharing as much data as possible with similar objects", "Creating objects faster", "Adding thread safety", "Simplifying the API"], correctIndex: 0, explanation: "It caches intrinsic state (like character font/size in a text editor) to save memory." },
    { question: "Which pattern lets you traverse elements of a collection without exposing its underlying representation?", options: ["Visitor", "Iterator", "Composite", "Proxy"], correctIndex: 1, explanation: "Iterator decouples the traversal algorithms from the collection data structures." },
    { question: "In MVC architecture, what does the Controller do?", options: ["Renders the UI", "Stores the database credentials", "Acts as an interface between Model and View components to process all the business logic and incoming requests", "Holds the schema of the database"], correctIndex: 2, explanation: "It receives input, manipulates the model, and updates the view." },
    { question: "What is a God Object (or God Class)?", options: ["A class that controls too much or knows too much, violating the Single Responsibility Principle", "A class representing the database", "The main method", "A perfectly optimized class"], correctIndex: 0, explanation: "It's an anti-pattern where one class becomes a massive dumping ground for logic." },
    { question: "What is the Adapter pattern used for?", options: ["To adapt to different screen sizes", "To convert the interface of a class into another interface clients expect", "To connect to different databases automatically", "To mock objects in tests"], correctIndex: 1, explanation: "Adapter allows classes with incompatible interfaces to work together." }
  ]
};
